## ============================================================
## ADC Encode Clock Output : FPGA -> FL9627
## ============================================================

set_property PACKAGE_PIN H18 [get_ports adc1_clk_ref]
set_property PACKAGE_PIN F11 [get_ports adc2_clk_ref]

set_property IOSTANDARD LVCMOS18 [get_ports {adc1_clk_ref adc2_clk_ref}]
set_property SLEW FAST [get_ports {adc1_clk_ref adc2_clk_ref}]
set_property DRIVE 8 [get_ports {adc1_clk_ref adc2_clk_ref}]


## ============================================================
## ZCU104 System Clock Input
## create_clock is generated by clk_wiz_0_in_context.xdc
## ============================================================

set_property PACKAGE_PIN F23 [get_ports sys_clk_p]
set_property PACKAGE_PIN E23 [get_ports sys_clk_n]
set_property IOSTANDARD LVDS [get_ports {sys_clk_p sys_clk_n}]


## ============================================================
## ADC1 DCO Input : FL9627 -> FPGA
## ============================================================

set_property PACKAGE_PIN F17 [get_ports adc1_clk_p]
set_property PACKAGE_PIN F16 [get_ports adc1_clk_n]

set_property IOSTANDARD LVDS [get_ports {adc1_clk_p adc1_clk_n}]
set_property DIFF_TERM TRUE [get_ports {adc1_clk_p adc1_clk_n}]

create_clock -name adc1_dco_clk -period 8.000 [get_ports adc1_clk_p]


## ============================================================
## ADC1 LVDS Data Input
## ============================================================

set_property PACKAGE_PIN L20 [get_ports {adc1_data_p[0]}]
set_property PACKAGE_PIN K20 [get_ports {adc1_data_n[0]}]
set_property PACKAGE_PIN H19 [get_ports {adc1_data_p[1]}]
set_property PACKAGE_PIN G19 [get_ports {adc1_data_n[1]}]
set_property PACKAGE_PIN K17 [get_ports {adc1_data_p[2]}]
set_property PACKAGE_PIN J17 [get_ports {adc1_data_n[2]}]
set_property PACKAGE_PIN L17 [get_ports {adc1_data_p[3]}]
set_property PACKAGE_PIN L16 [get_ports {adc1_data_n[3]}]
set_property PACKAGE_PIN L15 [get_ports {adc1_data_p[4]}]
set_property PACKAGE_PIN K15 [get_ports {adc1_data_n[4]}]
set_property PACKAGE_PIN E18 [get_ports {adc1_data_p[5]}]
set_property PACKAGE_PIN E17 [get_ports {adc1_data_n[5]}]
set_property PACKAGE_PIN J16 [get_ports {adc1_data_p[6]}]
set_property PACKAGE_PIN J15 [get_ports {adc1_data_n[6]}]
set_property PACKAGE_PIN H16 [get_ports {adc1_data_p[7]}]
set_property PACKAGE_PIN G16 [get_ports {adc1_data_n[7]}]
set_property PACKAGE_PIN G18 [get_ports {adc1_data_p[8]}]
set_property PACKAGE_PIN F18 [get_ports {adc1_data_n[8]}]
set_property PACKAGE_PIN A13 [get_ports {adc1_data_p[9]}]
set_property PACKAGE_PIN A12 [get_ports {adc1_data_n[9]}]
set_property PACKAGE_PIN G15 [get_ports {adc1_data_p[10]}]
set_property PACKAGE_PIN F15 [get_ports {adc1_data_n[10]}]
set_property PACKAGE_PIN C13 [get_ports {adc1_data_p[11]}]
set_property PACKAGE_PIN C12 [get_ports {adc1_data_n[11]}]

set_property IOSTANDARD LVDS [get_ports {adc1_data_p[*]}]
set_property IOSTANDARD LVDS [get_ports {adc1_data_n[*]}]
set_property DIFF_TERM TRUE [get_ports {adc1_data_p[*]}]
set_property DIFF_TERM TRUE [get_ports {adc1_data_n[*]}]


## ============================================================
## ADC1 SPI
## ============================================================

set_property PACKAGE_PIN K19 [get_ports adc1_spi_ce]
set_property PACKAGE_PIN H17 [get_ports adc1_spi_sclk]
set_property PACKAGE_PIN K18 [get_ports adc1_spi_io]

set_property IOSTANDARD LVCMOS18 [get_ports {adc1_spi_ce adc1_spi_sclk adc1_spi_io}]


## ============================================================
## ADC2 DCO Input : FL9627 -> FPGA
## ============================================================

set_property PACKAGE_PIN D11 [get_ports adc2_clk_p]
set_property PACKAGE_PIN D10 [get_ports adc2_clk_n]

set_property IOSTANDARD LVDS [get_ports {adc2_clk_p adc2_clk_n}]
set_property DIFF_TERM TRUE [get_ports {adc2_clk_p adc2_clk_n}]

create_clock -name adc2_dco_clk -period 8.000 [get_ports adc2_clk_p]


## ============================================================
## ADC2 LVDS Data Input
## ============================================================

set_property PACKAGE_PIN F12 [get_ports {adc2_data_p[0]}]
set_property PACKAGE_PIN E12 [get_ports {adc2_data_n[0]}]
set_property PACKAGE_PIN D12 [get_ports {adc2_data_p[1]}]
set_property PACKAGE_PIN C11 [get_ports {adc2_data_n[1]}]
set_property PACKAGE_PIN A8  [get_ports {adc2_data_p[2]}]
set_property PACKAGE_PIN A7  [get_ports {adc2_data_n[2]}]
set_property PACKAGE_PIN H13 [get_ports {adc2_data_p[3]}]
set_property PACKAGE_PIN H12 [get_ports {adc2_data_n[3]}]
set_property PACKAGE_PIN B10 [get_ports {adc2_data_p[4]}]
set_property PACKAGE_PIN A10 [get_ports {adc2_data_n[4]}]
set_property PACKAGE_PIN B9  [get_ports {adc2_data_p[5]}]
set_property PACKAGE_PIN B8  [get_ports {adc2_data_n[5]}]
set_property PACKAGE_PIN C7  [get_ports {adc2_data_p[6]}]
set_property PACKAGE_PIN C6  [get_ports {adc2_data_n[6]}]
set_property PACKAGE_PIN B6  [get_ports {adc2_data_p[7]}]
set_property PACKAGE_PIN A6  [get_ports {adc2_data_n[7]}]
set_property PACKAGE_PIN K10 [get_ports {adc2_data_p[8]}]
set_property PACKAGE_PIN J10 [get_ports {adc2_data_n[8]}]
set_property PACKAGE_PIN M13 [get_ports {adc2_data_p[9]}]
set_property PACKAGE_PIN L13 [get_ports {adc2_data_n[9]}]
set_property PACKAGE_PIN F7  [get_ports {adc2_data_p[10]}]
set_property PACKAGE_PIN E7  [get_ports {adc2_data_n[10]}]
set_property PACKAGE_PIN E9  [get_ports {adc2_data_p[11]}]
set_property PACKAGE_PIN D9  [get_ports {adc2_data_n[11]}]

set_property IOSTANDARD LVDS [get_ports {adc2_data_p[*]}]
set_property IOSTANDARD LVDS [get_ports {adc2_data_n[*]}]
set_property DIFF_TERM TRUE [get_ports {adc2_data_p[*]}]
set_property DIFF_TERM TRUE [get_ports {adc2_data_n[*]}]


## ============================================================
## ADC2 SPI
## ============================================================

set_property PACKAGE_PIN E10 [get_ports adc2_spi_ce]
set_property PACKAGE_PIN A11 [get_ports adc2_spi_sclk]
set_property PACKAGE_PIN B11 [get_ports adc2_spi_io]

set_property IOSTANDARD LVCMOS18 [get_ports {adc2_spi_ce adc2_spi_sclk adc2_spi_io}]


## ============================================================
## Temporary clock route override
## ============================================================

set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets IBUFDS_adc2_clk/O]